name: ecr ecs deploy
on:
    push:
      branches: [main]
permissions:
    contents: read
    id-token: write

env:
  REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO: ${{ secrets.AWS_ECR_REPO }}
  ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  
jobs:
  ecr-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Check out code
          uses: actions/checkout@v4
        
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws_region: ${{ env.REGION }}
            role-to-assume: ${{ env.ROLE_ARN }}
        
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
        
        - name: Build and push
          uses: docker/build-push-action@v7
          with:
           context: .
           push: true
           tags: |
             ${{ env.ECR_REPO }}:latest
             ${{ env.ECR_REPO }}:${{ github.run_number }}
